#!/usr/bin/env bash
# =============================================================================
# configure.sh — Configuration Module
# your-local-agent | github.com/you/your-local-agent
#
# Configures Aider to point at local Llama.cpp server.
# Writes shell aliases for local-ai-start, local-ai-stop, etc.
# Reads variables exported by detect.sh and download.sh.
# Safe to run multiple times — never duplicates config entries.
# =============================================================================

set -euo pipefail

# -----------------------------------------------------------------------------
# Logging helpers
# -----------------------------------------------------------------------------

LOG_FILE="${HOME}/.local-ai/setup.log"
mkdir -p "$(dirname "$LOG_FILE")"

log()     { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >> "$LOG_FILE"; }
info()    { echo "  $*";      log "INFO  $*"; }
warn()    { echo "  ⚠️  $*";  log "WARN  $*"; }
fail()    { echo "  ❌  $*";  log "ERROR $*"; exit 1; }
ok()      { echo "  ✅  $*";  log "OK    $*"; }
section() { echo ""; echo "▶ $*"; echo ""; log "SECTION $*"; }

# -----------------------------------------------------------------------------
# Constants
# -----------------------------------------------------------------------------

LOCAL_AI_DIR="${HOME}/.local-ai"
LLAMA_BIN_DIR="${LOCAL_AI_DIR}/bin"
AIDER_CONFIG_DIR="${HOME}/.aider"
LLAMA_PORT=8080
LLAMA_CONTEXT=2048    # reduced for lower memory pressure and cooler operation
LLAMA_GPU_LAYERS=10   # reduced from 99 — keeps laptop cool, slower but stable
LLAMA_THREADS=4       # limits CPU threads to reduce heat

# -----------------------------------------------------------------------------
# Guard — ensure detect.sh and download.sh have been sourced
# -----------------------------------------------------------------------------

guard_prerequisites() {
  if [[ -z "${SHELL_TYPE:-}" || -z "${SHELL_PROFILE:-}" ]]; then
    fail "configure.sh requires SHELL_TYPE and SHELL_PROFILE from detect.sh. Run detect.sh first."
  fi

  if [[ -z "${MODEL_PATH:-}" || -z "${SELECTED_MODEL_FILE:-}" ]]; then
    fail "configure.sh requires MODEL_PATH and SELECTED_MODEL_FILE from download.sh. Run download.sh first."
  fi

  if [[ -z "${CHIP_TYPE:-}" ]]; then
    fail "configure.sh requires CHIP_TYPE from detect.sh. Run detect.sh first."
  fi
}

# -----------------------------------------------------------------------------
# Helper — write a line to a file only if it doesn't already exist
# -----------------------------------------------------------------------------

append_if_missing() {
  local line="$1"
  local file="$2"

  if ! grep -qF "$line" "$file" 2>/dev/null; then
    echo "$line" >> "$file"
    return 0   # line was added
  fi
  return 1     # line already existed
}

# -----------------------------------------------------------------------------
# 1. Configure Aider agent
# -----------------------------------------------------------------------------

configure_aider() {
  section "Configuring Aider Agent"

  mkdir -p "$AIDER_CONFIG_DIR"

  local aider_config_file="${AIDER_CONFIG_DIR}/.aider.conf.yml"
  local endpoint="http://localhost:${LLAMA_PORT}/v1"

  # Write Aider config — points to local Llama.cpp OpenAI-compatible API
  cat > "$aider_config_file" <<EOF
# your-local-agent — Aider configuration
# Auto-generated by configure.sh — safe to edit

openai-api-base: ${endpoint}
openai-api-key: local
model: openai/local
context-window: ${LLAMA_CONTEXT}
stream: true
no-auto-commits: false
dark-mode: true
EOF

  ok "Aider config written to ${aider_config_file}"
  log "Aider config: endpoint=${endpoint} model=openai/local"
}

# -----------------------------------------------------------------------------
# 2. Write shell aliases
# -----------------------------------------------------------------------------

write_aliases() {
  section "Setting Up Shell Aliases"

  if [[ "${SHELL_TYPE}" == "fish" ]]; then
    write_fish_instructions
    return
  fi

  local model_path="${MODEL_PATH}"
  local port="${LLAMA_PORT}"
  local gpu_layers="${LLAMA_GPU_LAYERS}"
  local context="${LLAMA_CONTEXT}"
  local threads="${LLAMA_THREADS}"

  # Adjust GPU layers for Intel — use CPU only
  if [[ "${CHIP_TYPE}" == "intel" ]]; then
    gpu_layers=0
    warn "Intel Mac detected — GPU offloading disabled. Using CPU inference."
  fi

  # Build the alias block
  # Using a marker so we can detect and avoid duplicating on re-runs
  local marker="# your-local-agent aliases"

  if grep -qF "$marker" "${SHELL_PROFILE}" 2>/dev/null; then
    info "Aliases already present in ${SHELL_PROFILE} — updating..."
    remove_existing_aliases
  fi

  info "Writing aliases to ${SHELL_PROFILE}..."

  cat >> "${SHELL_PROFILE}" <<EOF

${marker}
# Start Llama.cpp server and launch Aider in current project folder
alias local-ai-start='${LLAMA_BIN_DIR}/llama-server -m "${model_path}" --port ${port} -ngl ${gpu_layers} -c ${context} --threads ${threads} > "${LOCAL_AI_DIR}/server.log" 2>&1 & echo "Starting model server..." && sleep 8 && aider --openai-api-base http://localhost:${port}/v1 --openai-api-key local --model openai/local'

# Stop the Llama.cpp server
alias local-ai-stop='pkill -f "llama-server" && echo "Server stopped."'

# Check if the server is running and healthy
alias local-ai-status='curl -s http://localhost:${port}/health && echo "" || echo "Server is not running. Run local-ai-start first."'

# Update your-local-agent to the latest version
alias local-ai-update='curl -fsSL https://raw.githubusercontent.com/you/your-local-agent/main/update.sh | bash'

# Show which model is loaded and server info
alias local-ai-info='echo "Model : ${SELECTED_MODEL_FILE}" && echo "Server: http://localhost:${port}" && echo "Log   : ${LOCAL_AI_DIR}/server.log"'
# end your-local-agent aliases
EOF

  ok "Aliases written to ${SHELL_PROFILE}"

  # Source profile in current session
  source_profile
}

remove_existing_aliases() {
  # Create temp file with restricted permissions to prevent race condition
  local tmp_file
  tmp_file="$(mktemp)"
  chmod 600 "$tmp_file"

  python3 - <<EOF
start_marker = "# your-local-agent aliases"
end_marker = "# end your-local-agent aliases"
inside = False
with open("${SHELL_PROFILE}") as f:
    lines = f.readlines()

with open("${tmp_file}", "w") as f:
    for line in lines:
        if start_marker in line:
            inside = True
        if not inside:
            f.write(line)
        if end_marker in line:
            inside = False
EOF

  mv "$tmp_file" "${SHELL_PROFILE}"
  info "Removed existing alias block for clean update"
}

source_profile() {
  info "Activating aliases in current session..."

  # shellcheck source=/dev/null
  source "${SHELL_PROFILE}" 2>/dev/null || \
    warn "Could not source ${SHELL_PROFILE} automatically. Run 'source ${SHELL_PROFILE}' or restart your terminal."

  ok "Aliases active"
}

# -----------------------------------------------------------------------------
# 3. Fish shell — manual instructions fallback
# -----------------------------------------------------------------------------

write_fish_instructions() {
  warn "Fish shell detected — automatic alias setup is not yet supported."
  echo ""
  echo "  Add these functions to your Fish config manually:"
  echo "  File: ~/.config/fish/config.fish"
  echo ""
  echo "  ──────────────────────────────────────────────────"
  echo "  function local-ai-start"
  echo "      ${LLAMA_BIN_DIR}/llama-server -m \"${MODEL_PATH}\" \\"
  echo "          --port ${LLAMA_PORT} -ngl ${LLAMA_GPU_LAYERS} \\"
  echo "          -c ${LLAMA_CONTEXT} &"
  echo "      sleep 5"
  echo "      aider --openai-api-base http://localhost:${LLAMA_PORT}/v1 --openai-api-key local --model openai/local"
  echo "  end"
  echo ""
  echo "  function local-ai-stop"
  echo "      pkill -f llama-server"
  echo "  end"
  echo ""
  echo "  function local-ai-status"
  echo "      curl -s http://localhost:${LLAMA_PORT}/health"
  echo "  end"
  echo "  ──────────────────────────────────────────────────"
  echo ""
  log "Fish shell — printed manual alias instructions"
}

# -----------------------------------------------------------------------------
# 4. Create local-ai state directory and config file
# -----------------------------------------------------------------------------

create_state_dir() {
  section "Creating State Directory"

  mkdir -p "${LOCAL_AI_DIR}"

  # Write a state file tracking what's installed
  # This is used by update.sh and for diagnostics
  cat > "${LOCAL_AI_DIR}/state.json" <<EOF
{
  "installed_at": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")",
  "model_id": "${SELECTED_MODEL_ID}",
  "model_file": "${SELECTED_MODEL_FILE}",
  "model_path": "${MODEL_PATH}",
  "chip_type": "${CHIP_TYPE}",
  "ram_gb": "${DETECTED_RAM_GB}",
  "macos_version": "${MACOS_VERSION}",
  "shell_type": "${SHELL_TYPE}",
  "shell_profile": "${SHELL_PROFILE}",
  "llama_port": ${LLAMA_PORT},
  "repo_version": "1.0.0"
}
EOF

  ok "State saved to ${LOCAL_AI_DIR}/state.json"
  log "State file written"
}

# -----------------------------------------------------------------------------
# 5. Port conflict check
# -----------------------------------------------------------------------------

check_port() {
  section "Checking Port Availability"

  if lsof -i ":${LLAMA_PORT}" &>/dev/null; then
    warn "Port ${LLAMA_PORT} is already in use by another process."
    warn "This may cause conflicts when starting the server."
    warn "Run 'local-ai-stop' or find and kill the process using port ${LLAMA_PORT}."
    warn "  → lsof -i :${LLAMA_PORT}"
  else
    ok "Port ${LLAMA_PORT} is available"
  fi
}

# -----------------------------------------------------------------------------
# 6. Summary
# -----------------------------------------------------------------------------

print_configure_summary() {
  echo ""
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  Configuration Summary"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  Aider Config      : ${AIDER_CONFIG_DIR}/.aider.conf.yml"
  echo "  Shell Profile     : ${SHELL_PROFILE}"
  echo "  State File        : ${LOCAL_AI_DIR}/state.json"
  echo "  Server Log        : ${LOCAL_AI_DIR}/server.log"
  echo "  Server Port       : ${LLAMA_PORT}"
  echo "  Llama Binaries    : ${LLAMA_BIN_DIR}"
  echo ""
  echo "  Available commands after setup:"
  echo "    local-ai-start  → start server and launch Aider"
  echo "    local-ai-stop   → stop the server"
  echo "    local-ai-status → check if server is running"
  echo "    local-ai-info   → show current model and server info"
  echo "    local-ai-update → update to latest version"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  log "Configuration complete"
}

# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------

main() {
  echo ""
  echo "⚙️  Configuring your local agent..."
  echo ""

  guard_prerequisites
  check_port
  configure_aider
  write_aliases
  create_state_dir
  print_configure_summary
}

main
